repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.0
    hooks:
      - id: prettier
        files: assets/javascript
        types: [javascript]
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.27.0
    hooks:
      - id: eslint
        files: assets/javascript
        additional_dependencies:
          - eslint@7.25.0
          - eslint-config-prettier@8.3.0
          - eslint-plugin-prettier@3.4.0
        types: [javascript]
  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        additional_dependencies:
          - stylelint@13.13.0
          - stylelint-config-sass-guidelines@8.0.0
          - stylelint-config-standard@22.0.0
