version: '2'
services:

  contact_forms:
    build:
      context: .
      dockerfile: ./compose/development/django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://postgres:5432 -wait tcp://redis:6379 -timeout 120s
    env_file:
      - ./.envs/.development/.django
      - ./.envs/.development/.postgres
    depends_on:
      - postgres
      - redis
    command: /app/compose/development/django/start.sh

  postgres:
    image: postgres:10
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=contact_forms

  redis:
    image: redis:3.2
    restart: unless-stopped
    ports:
      - "6379:6379"

  dockerhost:
      image: qoomon/docker-host
      cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
      mem_limit: 8M
      restart: on-failure
  tcp_message_emitter:
      depends_on: [ dockerhost ]
      image: alpine
      command: [ "sh", "-c", "while :; do date; sleep 1; done | nc 'dockerhost' 2323 -v"]
  udp_message_emitter:
      depends_on: [ dockerhost ]
      image: alpine
      command: [ "sh", "-c", "while :; do date; sleep 1; done | nc 'dockerhost' 5353 -u -v"]
