version: "2"
services:
  contact_forms:
    build:
      context: .
      dockerfile: ./compose/development/django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://redis:6379 -timeout 120s
    env_file:
      - .env
    depends_on:
      - redis
    command: /app/compose/development/django/start.sh

  redis:
    image: redis:3.2
