version: "2"
services:
  contact_forms:
    build:
      context: .
      dockerfile: ./compose/development/django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    command: /app/compose/development/django/start.sh
    stdin_open: true
    tty: true
  webpack:
    image: node:18.17.0
    command:
      bash -c "
        npm install
        && npm run dev
      "
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
