version: "2"
services:
  contact_forms:
    build:
      context: .
      dockerfile: ./compose/development/django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://postgres:5432 -wait tcp://redis:6379 -timeout 120s
    env_file:
      - ./.envs/.development/.django
      - ./.envs/.development/.postgres
    environment:
      - DJANGO_SETTINGS_MODULE
    depends_on:
      - postgres
      - redis
    command: /app/compose/development/django/start.sh

  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=contact_forms
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"

volumes:
  pgdata:
