version: "2"
services:
  contact_forms:
    build:
      context: .
      dockerfile: ./compose/test/django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://postgres:5432 -wait tcp://es:9200 -wait tcp://redis:6379 -timeout 120s
    env_file:
      - .env.test
    depends_on:
      - postgres
      - es
      - redis
    command: /app/compose/test/django/start.sh

  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    env_file:
      - .env.test

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    ports:
      - "9200:9200"

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
