version: "2"
services:
  contact_forms:
    build:
      context: .
      dockerfile: ./compose/test/django/Dockerfile
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://redis:6379 -timeout 120s
    env_file:
      - .env.test
    depends_on:
      - redis
      - webpack
    command: /app/compose/test/django/start.sh
  webpack:
    image: node:14
    command:
      bash -c "
        npm set unsafe-perm true
        && npm install
        && npm run dev
      "
    volumes:
      - .:/app
    working_dir: /app
  redis:
    image: redis:3.2
