version: "2"
services:
  contact_forms:
    build:
      context: .
      dockerfile: ./compose/automation/django/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: dockerize -wait tcp://es:9200 -wait tcp://redis:6379 -timeout 120s
    env_file:
      - .env.test
    depends_on:
      - es
      - redis
    command: /app/compose/automation/django/start.sh

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    restart: always
    ports:
      - "9200:9200"

  redis:
    image: redis:3.2
    restart: always
    ports:
      - "6379:6379"
