# ~/.circleci/config.yml
version: 2
aliases:
  - &redis_version              redis:3.2.10
  - &postgres_version           circleci/postgres:10
  - &python_version             circleci/python:3.6

  - &app_base_envs
    ADMIN_ENABLED: True
    DEBUG: True
    RESTRICT_ADMIN: False
    HMRC_TAX_FORM_URL: https://www.tax.service.gov.uk/shortforms/form/CITEX_CGEF
    DISABLE_COLLECTSTATIC: 1
    DJANGO_SECRET_KEY: DJANGO_SECRET_KEY
    DJANGO_SETTINGS_MODULE: config.settings.docker_development
    DJANGO_BASE_DIR: /app
    DIT_HELPDESK_ADMIN_PASSWORD: DIT_HELPDESK_ADMIN_PASSWORD
    POSTGRES_HOST: DJANGO_POSTGRES_HOST
    POSTGRES_DB: DJANGO_POSTGRES_DATABASE
    POSTGRES_USER: DJANGO_POSTGRES_USER
    POSTGRES_PASSWORD: DJANGO_POSTGRES_PASSWORD
    POSTGRES_PORT: DJANGO_POSTGRES_PORT

  # Redis container
  - &docker_redis
    image: *redis_version
    environment:
      REDIS_URL: "redis://localhost:6379/"

  # Postgres container
  - &docker_postgres
    image: *postgres_version
    name: postgres
    environment:
      POSTGRES_DB: contact_forms
      POSTGRES_HOST_AUTH_METHOD: trust

  # Python container
  - &docker_python
    image: *python_version

  # Contact forms test container
  - &docker_contact_forms_test
    image: ukti/dit-contact-forms-test:latest

  # Step for ui test* jobs
  - &wait_for_backend
    run:
      name: Wait for backend
      command: dockerize -wait http://localhost:8000 -timeout 300s

jobs:
  unit_tests:
    docker:
      - <<: *docker_python
        environment: *app_base_envs
      - *docker_postgres
      - *docker_redis
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - v1-dependencies-{{ .Branch }}-{{ checksum "requirements/development.txt" }}
      - run:
          command: pipenv install --system --dev --deploy
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "requirements/development.txt" }}
          paths:
            - "."
      - run:
          name: Running tests
          command:
            coverage run manage.py test core.tests.test_admin_ip_middleware:AdminIPMiddlewareTestCase.test_ip_restriction_valid_ip --settings=config.settings.test
      - run:
          name: Generate coverage
          command: |
            coverage report
            coverage xml -o test-reports/coverage.xml
            coverage html -d test-reports/coverage_html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  ui_tests:
    docker:
      - <<: *docker_contact_forms_test
        environment: *app_base_envs
      - *docker_postgres
      - *docker_redis
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "requirements/development.txt" }}
      - run:
          command: pipenv install --system --dev --deploy
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "requirements/development.txt" }}
          paths:
            - "."
      - run:
          name: Start app
          command:
            ./compose/automation/django/start.sh
          background: true
      - *wait_for_backend
      - run:
          name: Run tests
          command: |
            export PATH=$PATH:$HOME/bin
            pytest ui_test/specs
      - store_artifacts:
          path: screenshots

# CircleCI workflows
workflows:
  version: 2
  helpdesk:
    jobs:
      - unit_tests
      - ui_tests
