# ~/.circleci/config.yml
version: 2
aliases:
  - &redis_version              redis:4.0
  - &python_version             cimg/python:3.12

  - &app_base_envs
    DEBUG: True
    HMRC_TAX_FORM_URL: https://www.tax.service.gov.uk/shortforms/form/CITEX_CGEF
    HMRC_TARIFF_CLASSIFICATION_SERVICE_URL: https://www.gov.uk/guidance/ask-hmrc-for-advice-on-classifying-your-goods
    DISABLE_COLLECTSTATIC: 1
    DJANGO_SECRET_KEY: DJANGO_SECRET_KEY # pragma: allowlist secret
    DJANGO_SETTINGS_MODULE: config.settings.docker_development
    DIT_HELPDESK_ADMIN_PASSWORD: DIT_HELPDESK_ADMIN_PASSWORD # pragma: allowlist secret
    FORM_URL: http://contact.check-duties-customs-exporting-goods.service.gov.uk/

  # Redis container
  - &docker_redis
    image: *redis_version
    environment:
      REDIS_URL: "redis://localhost:6379/"

  # Python container
  - &docker_python
    image: *python_version

  # Contact forms test container
  - &docker_contact_forms_test
    image: ukti/dit-contact-forms-test:latest

  # Step for ui test* jobs
  - &wait_for_backend
    run:
      name: Wait for backend
      command: dockerize -wait http://localhost:8000 -timeout 300s

jobs:
  unit_tests:
    docker:
      - image: cimg/node:18.17.1-browsers
      #- <<: *docker_python
        environment: *app_base_envs
      - *docker_redis
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install system deps
          command:
            sudo apt-get update && sudo apt-get install -y nodejs npm
      - run:
          command: |
            pip install pipenv
            pipenv install --system --dev --deploy
      - run:
          name: Webpack build
          command:
            npm install && npm run build
      - run:
          name: Running tests
          command: |
            pip install pytest
            pytest
      - run:
          name: Generate coverage
          command: |
            pip install coverage
            coverage report
            coverage xml -o test-reports/coverage.xml
            coverage html -d test-reports/coverage_html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  ui_tests:
    docker:
      - image: cimg/node:18.17.1-browsers
        environment: *app_base_envs
      - *docker_redis
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install system deps
          command: |
            sudo apt-get update
            sudo apt install chromium-browser
            sudo apt install chromium-chromedriver
            sudo apt install python3-pip
            sudo apt install python3-pytest
            sudo pip3 install pipenv
            sudo pip3 install selenium
      - run:
          name: Install Python deps
          command: |
            pipenv install --system --dev --deploy
      - run:
          name: Webpack build
          command: |
            npm install
            npm run build
      - run:
          name: Start app
          command:
            ./compose/automation/django/start.sh
          background: true
      - *wait_for_backend
      - run:
          name: Run tests
          # Removed the following commands from "Run tests" step - to be replaced
          # with new UI tests in TSS-2039
          # export PATH=$PATH:$HOME/bin
          # python3 -m pytest ui_test
          command:
            env
      - store_artifacts:
          path: screenshots

  format_checks:
    docker:
      - <<: *docker_python
        environment: *app_base_envs
    working_directory: ~/app
    steps:
      - checkout
      - run:
          command: |
            pip install pre-commit
      - restore_cache:
          keys:
            - pre-commit-cache-{{ arch }}-{{ .Branch }}
      - run:
          name: Formatting checks
          command: pre-commit run --from-ref origin/HEAD --to-ref HEAD
      - save_cache:
          key: pre-commit-cache-{{ arch }}-{{ .Branch }}
          paths:
            - ~/.cache/pre-commit

# CircleCI workflows
workflows:
  version: 2
  helpdesk:
    jobs:
      - unit_tests
      - ui_tests
      - format_checks
