# ~/.circleci/config.yml
version: 2
aliases:
  - &redis_version              redis:3.2.10
  - &postgres_version           circleci/postgres:10
  - &python_version             circleci/python:3.6

  - &app_base_envs
    ADMIN_ENABLED: True
    DEBUG: True
    RESTRICT_ADMIN: False
    HMRC_TAX_FORM_URL: https://www.tax.service.gov.uk/shortforms/form/CITEX_CGEF
    DISABLE_COLLECTSTATIC: 1
    DJANGO_SECRET_KEY: DJANGO_SECRET_KEY
    DJANGO_SETTINGS_MODULE: config.settings.docker_development
    DJANGO_BASE_DIR: /app
    DIT_HELPDESK_ADMIN_PASSWORD: DIT_HELPDESK_ADMIN_PASSWORD
    DJANGO_POSTGRES_HOST: DJANGO_POSTGRES_HOST
    DJANGO_POSTGRES_DATABASE: DJANGO_POSTGRES_DATABASE
    DJANGO_POSTGRES_USER: DJANGO_POSTGRES_USER
    DJANGO_POSTGRES_PASSWORD: DJANGO_POSTGRES_PASSWORD
    DJANGO_POSTGRES_PORT: DJANGO_POSTGRES_PORT

  # Redis container
  - &docker_redis
    image: *redis_version
    environment:
      REDIS_URL: "redis://localhost:6379/"

  # Postgres container
  - &docker_postgres
    image: *postgres_version
    name: postgres
    environment:
      POSTGRES_DB: helpdesk

  # Python container
  - &docker_python
    image: *python_version

  # Step for ui test* jobs
  - &wait_for_backend
    run:
      name: Wait for backend
      command: dockerize -wait http://localhost:8000 -timeout 300s

jobs:
  build:
    docker:
      - <<: *docker_python
        environment: *app_base_envs
      - *docker_postgres
      - *docker_redis
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "requirements/development.txt" }}
            - v1-dependencies-{{ .Branch }}-
            - v1-dependencies-
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/development.txt
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "requirements/development.txt" }}
          paths:
            - "venv"
      - run:
          name: Start app
          command: | 
            . venv/bin/activate
            npm install
            npm run build
            python manage.py runserver_plus 0.0.0.0:8000
          background: true
      - *wait_for_backend
