# ~/.circleci/config.yml
version: 2
aliases:
  - &redis_version              redis:3.2.10
  - &python_version             circleci/python:3.6

  - &app_base_envs
    DEBUG: True
    HMRC_TAX_FORM_URL: https://www.tax.service.gov.uk/shortforms/form/CITEX_CGEF
    HMRC_TARIFF_CLASSIFICATION_SERVICE_URL: https://www.gov.uk/guidance/ask-hmrc-for-advice-on-classifying-your-goods
    DISABLE_COLLECTSTATIC: 1
    DJANGO_SECRET_KEY: DJANGO_SECRET_KEY
    DJANGO_SETTINGS_MODULE: config.settings.docker_development
    DIT_HELPDESK_ADMIN_PASSWORD: DIT_HELPDESK_ADMIN_PASSWORD
    FORM_URL: http://contact.check-duties-customs-exporting-goods.service.gov.uk/

  # Redis container
  - &docker_redis
    image: *redis_version
    environment:
      REDIS_URL: "redis://localhost:6379/"

  # Python container
  - &docker_python
    image: *python_version

  # Contact forms test container
  - &docker_contact_forms_test
    image: ukti/dit-contact-forms-test:latest

  # Step for ui test* jobs
  - &wait_for_backend
    run:
      name: Wait for backend
      command: dockerize -wait http://localhost:8000 -timeout 300s

jobs:
  unit_tests:
    docker:
      - <<: *docker_python
        environment: *app_base_envs
      - *docker_redis
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install system deps
          command:
            sudo apt-get update && sudo apt-get install -y nodejs npm
      - run:
          command: pipenv install --system --dev --deploy
      - run:
          name: Webpack build
          command:
            npm install && npm run build
      - run:
          name: Running tests
          command:
            coverage run manage.py test contact_forms --settings=config.settings.test
      - run:
          name: Generate coverage
          command: |
            coverage report
            coverage xml -o test-reports/coverage.xml
            coverage html -d test-reports/coverage_html
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

  ui_tests:
    docker:
      - image: joyzoursky/python-chromedriver
        environment: *app_base_envs
      - *docker_redis
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install system deps
          command: |
            apt-get update
            apt-get install -y nodejs npm
            pip install pipenv
            export DOCKERIZE_VERSION=v0.6.1
            wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
      - run:
          name: Install Python deps
          command: pipenv install --system --dev --deploy
      - run:
          name: Webpack build
          command: |
            npm install
            npm run build
      - run:
          name: Start app
          command:
            ./compose/automation/django/start.sh
          background: true
      - *wait_for_backend
      - run:
          name: Run tests
          command: |
            export PATH=$PATH:$HOME/bin
            pytest ui_test/specs
      - store_artifacts:
          path: screenshots

# CircleCI workflows
workflows:
  version: 2
  helpdesk:
    jobs:
      - unit_tests
      - ui_tests
