# Generated by Django 2.2.2 on 2019-08-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    def initial_entry(apps, schema_editor):
        HealthCheck = apps.get_model('healthcheck', 'HealthCheck')
        HealthCheck.objects.create(health_check_field=True)

    dependencies = [
        ('healthcheck', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_entry),
    ]
